


apiVersion: v1
kind: Service
metadata:
  name: abctech-service
  namespace: abctech-namespace
spec:
 selector:
   app: abc
 type: NodePort
 ports:
  - nodePort: 31321
    port: 8080
    targetPort: 8080
